import json
import requests
import logging

def format_with_local_ai(json_path, model_name="qwen2.5-coder:7b"):
    """
    Reads the generated knowledge JSON and sends it to a local Ollama instance.
    """
    logging.info("Reading knowledge base from: %s", json_path)
    
    try:
        with open(json_path, "r", encoding="utf-8") as f:
            knowledge = json.load(f)
    except FileNotFoundError:
        logging.error("Could not find the JSON file. Did you run the main script first?")
        return None

    # Construct the prompt for Qwen
    # We dump the JSON back to a string so the AI can read it
    system_prompt = (
        "You are an expert technical writer and researcher. "
        "Review the following JSON data containing Wikipedia summaries, news articles, and web scrapes. "
        "Synthesize this information into a beautifully formatted, highly detailed Markdown report. "
        "Do not repeat information. Organize it logically with clear headings."
    )
    
    user_prompt = f"Here is the raw data:\n\n{json.dumps(knowledge, indent=2)}"

    # The standard Ollama local endpoint
    ollama_url = "http://localhost:11434/api/generate"
    
    payload = {
        "model": model_name,
        "prompt": f"{system_prompt}\n\n{user_prompt}",
        "stream": False # Set to True if you want to handle streaming responses
    }

    logging.info("Sending data to local AI model: %s...", model_name)
    
    try:
        response = requests.post(ollama_url, json=payload, timeout=120)
        response.raise_for_status()
        
        result = response.json()
        final_text = result.get("response", "")
        
        logging.info("AI Generation Complete!")
        return final_text
        
    except requests.exceptions.ConnectionError:
        logging.error("Failed to connect to Ollama. Is the Ollama app running on your machine?")
        return None
    except Exception as e:
        logging.error("An error occurred during AI generation: %s", str(e))
        return None

# --- Example of how to run it ---
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    
    # Replace this with the actual path generated by your previous script
    TARGET_JSON = "reports/YourTopic_knowledge.json" 
    
    formatted_report = format_with_local_ai(TARGET_JSON)
    
    if formatted_report:
        # Save the AI's output to a markdown file
        output_file = "reports/Final_AI_Report.md"
        with open(output_file, "w", encoding="utf-8") as out:
            out.write(formatted_report)
        print(f"\nSuccess! AI report saved to {output_file}")